#!/usr/bin/expect -f

set timeout -1

spawn amplify add api

expect "Please select from one of the below mentioned services:"
send -- "GraphQL\r"
expect "Provide API name:"
send -- "tracktunes\r"
expect "Choose the default authorization type"
# selects IAM
send -- "\[B"
send -- "\[B"
send -- "\r"
expect "Do you want to configure advanced settings for the GraphQL API"
# selects additional changes
send -- "\[B"
send -- "\r"
expect "Configure additional auth types?"
send -- "y\r"
expect "Choose the additional authorization types you want to configure"
send -- "\[B"
send -- " "
send -- "\r"
expect "you want to use the default authentication and security configuration?"
send -- "\r"
expect "How do you want users to be able to sign in?"
send -- "\r"
expect "Do you want to configure advanced settings?"
send -- "\r"
expect "Enable conflict detection?"
send -- "\r"
expect "Do you have an annotated GraphQL schema?"
send -- "y\r"
expect "Provide your schema file path:"
send -- "schema.graphql\r"

interact
